### ISSUE TITLE
http 409 conflict

### ISSUE THREAD

**Issue by buuhsmead** [nicolaferraro/telegram-quickstart#1]
Could you please enlighten me on the http 409 error I get?
I cloned this repo on a local drive and changed the application.properties to contain the token of mine personal bot.
I got the same error in karaf 4.0.5.

2016-07-30 15:31:09.820  WARN 19371 --- [MnTlLeBWOX2yUsU] o.a.c.c.telegram.TelegramConsumer        : Consumer Consumer[telegram://bots/<token>] failed polling endpoint: telegram://bots/<token>. Will try again at next poll. Caused by: [javax.ws.rs.ClientErrorException - HTTP 409 Conflict]

javax.ws.rs.ClientErrorException: HTTP 409 Conflict
    at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_66]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_66]
    at org.apache.cxf.jaxrs.client.AbstractClient.convertToWebApplicationException(AbstractClient.java:504) ~[cxf-rt-rs-client-3.1.6.jar:3.1.6]
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:314) ~[cxf-rt-rs-client-3.1.6.jar:3.1.6]
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:793) ~[cxf-rt-rs-client-3.1.6.jar:3.1.6]
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:755) ~[cxf-rt-rs-client-3.1.6.jar:3.1.6]
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:228) ~[cxf-rt-rs-client-3.1.6.jar:3.1.6]
    at com.sun.proxy.$Proxy75.getUpdates(Unknown Source) ~[na:na]
    at org.apache.camel.component.telegram.service.TelegramServiceRestBotAPIAdapter.getUpdates(TelegramServiceRestBotAPIAdapter.java:54) ~[camel-telegram-2.18-SNAPSHOT.jar:2.18-SNAPSHOT]
    at org.apache.camel.component.telegram.TelegramConsumer.poll(TelegramConsumer.java:57) ~[camel-telegram-2.18-SNAPSHOT.jar:2.18-SNAPSHOT]
    at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175) [camel-core-2.18-SNAPSHOT.jar:2.18-SNAPSHOT]
    at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102) [camel-core-2.18-SNAPSHOT.jar:2.18-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_66]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_66]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by buuhsmead** [comment]
Doing some investigation I got the following response when calling by cUrl the botapi directly:
{"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active"}

Now I have to find the 'active webhook'. Is this because I configured something??

**Comment by buuhsmead** [comment]
Ok, my bad.
You can only use one of setUpdates or setWebhook. The documentation is clear on that.
To clean out the webhook the following cUrl can help:
curl -X GET https://api.telegram.org/bot12245:dfgfjdjdhd/setWebhook?url=

**Comment by buuhsmead** [comment]
Only use one of setUpdates or setWebhook.
